name: Bug Report
description: AB is not working as it should be
labels: ["bug"] 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what happened
      value: 
    validations:
      required: true
  - type: textarea
    id: errors
    attributes:
      label: Relevant errors
      description: Please copy and paste any relevant errors from the terminal. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: files
    attributes:
      label: Relevant files
      description: Drag any files into this box like screenshots or relevant databases
      placeholder: Share your files
      value: 
  - type: textarea
    id: conda-env
    attributes:
      label: Conda environment
      description: Please copy and paste the output from `conda list`. This will be automatically formatted into code, so no need for backticks.
      render: shell
