name: Bug report
description: File a bug report for AB.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what happened
    validations:
      required: true
  - type: textarea
    id: errors
    attributes:
      label: Relevant errors
      description: Please copy and paste any relevant errors from the terminal.
      placeholder: This will be automatically formatted into code, so no need to worry about the formatting.
      render: python
  - type: textarea
    id: files
    attributes:
      label: Relevant files
      description: Drag any relevant files into the box below like screenshots or relevant databases
      placeholder: Share your files
  - type: textarea
    id: conda-env
    attributes:
      label: Conda environment
      description: Please copy and paste the output from `conda list`.
      placeholder: This will be automatically formatted into code, so no need to worry about the formatting.
      render: shell
