blank_issues_enabled: true
contact_links:
  - name: Need help with using AB?
    url: https://github.com/LCA-ActivityBrowser/activity-browser/discussions
    about: Please ask and answer questions here.
