blank_issues_enabled: false
read_wiki:
  - name: Read the Wiki
    url: https://github.com/LCA-ActivityBrowser/activity-browser/wiki
    about: Learn how to use Activity Browser from our wiki.
contact_links:
  - name: How to use AB
    url: https://github.com/LCA-ActivityBrowser/activity-browser/discussions
    about: Ask the Activity Browser community for help.
