name: stable release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Build changelog from PRs with labels
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up conda-build environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          activate-environment: build
          environment-file: .github/conda-envs/build.yml
      - name: Build activity-browser stable
        run: |
          conda build recipe/
      - name: Upload to anaconda.org
        run: |
          anaconda -t ${{ secrets.CONDA_UPLOAD_TOKEN }} upload \
          /usr/share/miniconda/envs/build/conda-bld/noarch/*.tar.bz2
      - name: Update wiki
        run: |
          cd ..
          git clone https://github.com/$GITHUB_REPOSITORY.wiki.git
          yes | cp -rf activity-browser/activity_browser/docs/wiki/* activity-browser.wiki/
          cd activity-browser.wiki
          grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
          if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
            echo "Wiki documentation was not changed, documentation, not updating."
            set +e 
            pkill -9 -P $$ &> /dev/null || true 
            exit 0
          else 
            echo "Wiki documentation was changed, documentation, updating."
            git config --global user.name "$GITHUB_ACTOR"
            git config --global user.email "$(git log -n 1 --pretty=format:%ae)"            
            git status
            git add .
            git commit -m "Automated documentation update for $GITHUB_REF_NAME"
            git remote add origin-wiki "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.wiki"
            git push origin-wiki master
          fi
